extends Node


enum {BORING_ROOM, KEY_ROOM, LEVER_ROOM, SKULL_MAIN, SKULL_GIANT,
  	 SKULL_DWARF, TRAIN_ROOM, GOAT_ROOM, SCALE_MID, SCALE_SMALL, 
 	 SCALE_LARGE, DARK_HALLWAY}

# copy for type enforcement
enum DoorID {BORING_ROOM, KEY_ROOM, LEVER_ROOM, SKULL_MAIN, SKULL_GIANT,
	  SKULL_DWARF, TRAIN_ROOM, GOAT_ROOM, SCALE_MID, SCALE_SMALL, 
	  SCALE_LARGE, DARK_HALLWAY}

var map = { 
	DARK_HALLWAY: [BORING_ROOM, BORING_ROOM],
	BORING_ROOM : [KEY_ROOM, KEY_ROOM],
	KEY_ROOM: [BORING_ROOM, LEVER_ROOM],
	LEVER_ROOM: [BORING_ROOM, SKULL_MAIN],
	SKULL_MAIN: [TRAIN_ROOM, BORING_ROOM],
	TRAIN_ROOM: [GOAT_ROOM, SKULL_MAIN],
	GOAT_ROOM: [SCALE_MID, TRAIN_ROOM],
	SCALE_MID: [SCALE_SMALL, SCALE_LARGE],
	SCALE_LARGE: [SKULL_GIANT, SCALE_MID],
	SCALE_SMALL: [SCALE_MID, SKULL_DWARF],
	SKULL_DWARF: [GOAT_ROOM, SCALE_SMALL],
	SKULL_GIANT: [GOAT_ROOM, SCALE_LARGE]
}

# updated by the doors themselves during _ready call
var id_to_node = {
	DARK_HALLWAY: null,
	BORING_ROOM: null, KEY_ROOM: null, LEVER_ROOM: null, SKULL_MAIN: null,
	SKULL_GIANT: null, SKULL_DWARF: null, TRAIN_ROOM: null, GOAT_ROOM: null,
	SCALE_MID: null, SCALE_SMALL: null, SCALE_LARGE: null }
