extends Node


enum {BORING_ROOM, KEY_ROOM, LEVER_ROOM, SKULL_MAIN, SKULL_GIANT,
  	 SKULL_DWARF, TRAIN_ROOM, GOAT_ROOM, SCALE_MID, SCALE_SMALL, 
 	 SCALE_LARGE, GIANT_ROOM, DWARF_ROOM}

# copy for type enforcement
enum DoorID {BORING_ROOM, KEY_ROOM, LEVER_ROOM, SKULL_MAIN, SKULL_GIANT,
	  SKULL_DWARF, TRAIN_ROOM, GOAT_ROOM, SCALE_MID, SCALE_SMALL, 
	  SCALE_LARGE, GIANT_ROOM, DWARF_ROOM}

var map = { 
	BORING_ROOM : [KEY_ROOM, KEY_ROOM],
	KEY_ROOM: [BORING_ROOM, LEVER_ROOM],
	LEVER_ROOM: [BORING_ROOM, SKULL_MAIN],
	SKULL_MAIN: [BORING_ROOM, TRAIN_ROOM],
	TRAIN_ROOM: [SKULL_MAIN, GOAT_ROOM],
	GOAT_ROOM: [TRAIN_ROOM, SCALE_MID],
	SCALE_MID: [GIANT_ROOM, DWARF_ROOM],
	GIANT_ROOM: [SCALE_LARGE, SKULL_GIANT],
	DWARF_ROOM: [SCALE_SMALL, SKULL_DWARF],
	SKULL_DWARF: [GOAT_ROOM, SCALE_SMALL],
	SKULL_GIANT: [GOAT_ROOM, SCALE_LARGE],
	SCALE_LARGE: [SCALE_MID, GIANT_ROOM],
	SCALE_SMALL: [SCALE_MID, DWARF_ROOM]
}

# updated by the doors themselves during _ready call
var id_to_node = {
	BORING_ROOM: null, KEY_ROOM: null, LEVER_ROOM: null, SKULL_MAIN: null,
	SKULL_GIANT: null, SKULL_DWARF: null, TRAIN_ROOM: null, GOAT_ROOM: null,
	SCALE_MID: null, SCALE_SMALL: null, SCALE_LARGE: null, GIANT_ROOM: null,
	DWARF_ROOM:null
}
